# Generated by Django 3.2.4 on 2022-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
