# Generated by Django 3.2.4 on 2022-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220331_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
