# Generated by Django 3.2.4 on 2022-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220331_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcas',
            name='marca',
        ),
        migrations.AddField(
            model_name='marcas',
            name='nombre',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
    ]
