# Generated by Django 3.2.4 on 2022-03-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220331_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='img',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='marcas',
            name='nombre',
        ),
    ]
