# Generated by Django 3.2.4 on 2022-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.ImageField(null=True, upload_to='app/static/app/img/marcas'),
        ),
    ]
