# Generated by Django 3.2.4 on 2022-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_marcas_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
    ]
