# Generated by Django 3.2.4 on 2022-03-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='video',
        ),
    ]
