# Generated by Django 3.2.4 on 2022-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_productos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='videoid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
