# Generated by Django 3.2.4 on 2022-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_productos_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='videoid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
